version: '3.8'

services:

  php_8.2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: mysql://root:secret@database:3306/symfony_db?serverVersion=mariadb-10.9.4
      APP_SECRET: changeMe
      MAILER_DSN: smtp://:@mailcatcher:1025
      MESSENGER_TRANSPORT_DSN: doctrine://default
    ports:
      - "8001:80"
    volumes:
      - ./config:/var/www/config
      - ./src:/var/www/src
      - ./templates:/var/www/templates
      - ./tests:/var/www/tests
      - ./translations:/var/www/translations
      - ./public/build:/var/www/public/build
      - ./migrations:/var/www/migrations
    depends_on:
      - database

  database:
    image: mariadb:10.9.4
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: symfony_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
    ports:
      - "8080:80"
    depends_on:
      - database

  mailcatcher:
    image: schickling/mailcatcher
    restart: unless-stopped
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  db_data: